import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2, CalendarDays, ChartNoAxesCombined, CircleUserRound, MessageSquareText, Plus } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { api, initializeCsrf } from '../../api/client'
import { errorMessage } from '../../api/errors'
import { StatusBadge } from '../../components/StatusBadge'
import type { ApiEnvelope, Booking, FieldType, OwnerDashboard, OwnerProfile, Paginated, Review, SportsField } from '../../types/api'
import { Empty, PageTitle } from '../customer/CustomerPages'

const currency = new Intl.NumberFormat('vi-VN')

export function OwnerDashboardPage() {
  const dashboard = useQuery({ queryKey: ['owner', 'dashboard'], queryFn: async () => (await api.get<ApiEnvelope<OwnerDashboard>>('/field-owner/dashboard')).data.data })
  const data = dashboard.data
  return <><PageTitle icon={<ChartNoAxesCombined />} kicker="Tổng quan" title="Nhịp vận hành hôm nay" copy="Theo dõi sân, lượt đặt và doanh thu trong một màn hình." /><div className="stats-grid"><Stat label="Tổng số sân" value={data?.total_fields ?? 0} /><Stat label="Tổng lượt đặt" value={data?.total_bookings ?? 0} /><Stat label="Doanh thu" value={`${currency.format(data?.total_revenue ?? 0)}đ`} /><Stat label="Đơn tháng này" value={data?.current_month_bookings ?? 0} /></div><section className="data-panel"><div className="data-panel__head"><div><span>Hoạt động gần đây</span><h2>Yêu cầu đặt sân mới nhất</h2></div></div><BookingTable bookings={data?.recent_bookings ?? []} /></section></>
}

export function OwnerFieldsPage() {
  const client = useQueryClient()
  const [editing, setEditing] = useState<SportsField | 'new' | null>(null)
  const fields = useQuery({ queryKey: ['owner', 'fields'], queryFn: async () => (await api.get<Paginated<SportsField>>('/field-owner/fields')).data })
  const types = useQuery({ queryKey: ['field-types'], queryFn: async () => (await api.get<{ data: FieldType[] }>('/field-types')).data.data })
  const save = useMutation({ mutationFn: async ({ field, data }: { field: SportsField | 'new'; data: FormData }) => { await initializeCsrf(); if (field === 'new') return api.post('/field-owner/fields', data); data.append('_method', 'PUT'); return api.post(`/field-owner/fields/${field.id}`, data) }, onSuccess: () => { setEditing(null); void client.invalidateQueries({ queryKey: ['owner', 'fields'] }) } })
  const toggle = useMutation({ mutationFn: async (field: SportsField) => { await initializeCsrf(); return api.patch(`/field-owner/fields/${field.id}/toggle`) }, onSuccess: () => client.invalidateQueries({ queryKey: ['owner', 'fields'] }) })
  return <><PageTitle icon={<Building2 />} kicker="Nguồn cung" title="Sân của tôi" copy="Tạo, cập nhật và điều khiển trạng thái nhận lịch." action={<button className="button button--brand" onClick={() => setEditing('new')}><Plus size={16} /> Thêm sân</button>} /><section className="data-panel"><div className="table-wrap"><table><thead><tr><th>Sân</th><th>Loại</th><th>Giá/giờ</th><th>Kiểm duyệt</th><th>Hoạt động</th><th /></tr></thead><tbody>{fields.data?.data.map((field) => <tr key={field.id}><td><strong>{field.name}</strong><small>{field.address}</small></td><td>{field.field_type?.name}</td><td>{currency.format(field.price_per_hour)}đ</td><td><StatusBadge status={field.status} /></td><td><button className={`status ${field.is_active ? 'status--approved' : 'status--inactive'}`} onClick={() => toggle.mutate(field)}>{field.is_active ? 'Đang mở' : 'Đã đóng'}</button></td><td><button className="button button--ghost" onClick={() => setEditing(field)}>Chỉnh sửa</button></td></tr>)}</tbody></table></div></section>{!fields.isPending && !fields.data?.data.length && <Empty text="Hãy tạo sân đầu tiên để bắt đầu nhận lịch." />}{editing && <FieldModal field={editing} types={types.data ?? []} busy={save.isPending} error={save.isError ? errorMessage(save.error) : ''} onClose={() => setEditing(null)} onSubmit={(event) => { event.preventDefault(); save.mutate({ field: editing, data: new FormData(event.currentTarget) }) }} />}</>
}

function FieldModal({ field, types, busy, error, onClose, onSubmit }: { field: SportsField | 'new'; types: FieldType[]; busy: boolean; error: string; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void }) {
  const current = field === 'new' ? null : field
  return <div className="modal"><form className="modal__card modal__card--wide" onSubmit={onSubmit}><h2>{current ? 'Chỉnh sửa sân' : 'Thêm sân mới'}</h2><div className="form-grid"><label><span>Tên sân</span><input name="name" defaultValue={current?.name} required /></label><label><span>Loại sân</span><select name="field_type_id" defaultValue={current?.field_type?.id} required><option value="">Chọn loại sân</option>{types.map((type) => <option value={type.id} key={type.id}>{type.category?.name} · {type.name}</option>)}</select></label><label><span>Địa chỉ</span><input name="address" defaultValue={current?.address} required /></label><label><span>Giá mỗi giờ</span><input name="price_per_hour" type="number" defaultValue={current?.price_per_hour} required /></label></div><label><span>Mô tả</span><textarea name="description" defaultValue={current?.description ?? ''} /></label>{!current && <label><span>Hình ảnh</span><input name="images[]" type="file" accept="image/*" multiple /></label>}{error && <div className="notice notice--error">{error}</div>}<div className="modal__actions"><button className="button button--ghost" type="button" onClick={onClose}>Đóng</button><button disabled={busy} className="button button--brand">{busy ? 'Đang lưu...' : 'Lưu sân'}</button></div></form></div>
}

export function OwnerBookingsPage() {
  const client = useQueryClient()
  const [status, setStatus] = useState('')
  const bookings = useQuery({ queryKey: ['owner', 'bookings', status], queryFn: async () => (await api.get<Paginated<Booking>>(`/field-owner/bookings${status ? `?status=${status}` : ''}`)).data })
  const update = useMutation({ mutationFn: async ({ booking, status: next }: { booking: Booking; status: string }) => { await initializeCsrf(); return api.patch(`/field-owner/bookings/${booking.id}/status`, { status: next }) }, onSuccess: () => client.invalidateQueries({ queryKey: ['owner', 'bookings'] }) })
  return <><PageTitle icon={<CalendarDays />} kicker="Vận hành" title="Đơn đặt sân" copy="Xác nhận yêu cầu và hoàn thành lịch chơi của khách hàng." /><div className="toolbar"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Mọi trạng thái</option><option value="pending">Chờ xử lý</option><option value="confirmed">Đã xác nhận</option><option value="completed">Hoàn thành</option><option value="cancelled">Đã hủy</option><option value="rejected">Từ chối</option></select></div><section className="data-panel"><BookingTable bookings={bookings.data?.data ?? []} actions={(booking) => <>{booking.status === 'pending' && <><button className="button button--brand" onClick={() => update.mutate({ booking, status: 'confirmed' })}>Xác nhận</button><button className="button button--danger" onClick={() => update.mutate({ booking, status: 'rejected' })}>Từ chối</button></>}{booking.status === 'confirmed' && <button className="button button--dark" onClick={() => update.mutate({ booking, status: 'completed' })}>Hoàn thành</button>}</>} /></section></>
}

export function OwnerReviewsPage() {
  const reviews = useQuery({ queryKey: ['owner', 'reviews'], queryFn: async () => (await api.get<Paginated<Review>>('/field-owner/reviews')).data })
  return <><PageTitle icon={<MessageSquareText />} kicker="Phản hồi" title="Khách hàng nói gì?" copy="Lắng nghe trải nghiệm thật để cải thiện chất lượng sân." /><div className="review-grid">{reviews.data?.data.map((review) => <article className="review-card" key={review.id}><div><div className="avatar">{review.user?.name.slice(0, 1)}</div><span><strong>{review.user?.name}</strong><small>{new Date(review.created_at).toLocaleDateString('vi-VN')}</small></span><b>{'★'.repeat(review.rating)}</b></div><p>“{review.comment}”</p><small>Đánh giá cho <strong>{review.field?.name}</strong></small></article>)}</div>{!reviews.isPending && !reviews.data?.data.length && <Empty text="Chưa có phản hồi từ khách hàng." />}</>
}

export function OwnerProfilePage() {
  const client = useQueryClient()
  const profile = useQuery({ queryKey: ['owner', 'profile'], queryFn: async () => (await api.get<ApiEnvelope<OwnerProfile>>('/field-owner/profile')).data.data })
  const update = useMutation({ mutationFn: async (payload: Record<string, string>) => { await initializeCsrf(); return api.put('/field-owner/profile', payload) }, onSuccess: () => client.invalidateQueries({ queryKey: ['owner', 'profile'] }) })
  return <><PageTitle icon={<CircleUserRound />} kicker="Đối tác" title="Hồ sơ cơ sở" copy="Thông tin dùng trong quá trình kiểm duyệt và liên hệ với khách hàng." /><form key={profile.data?.id} className="panel-form panel-form--wide" onSubmit={(event) => { event.preventDefault(); update.mutate(Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>) }}><div className="profile-status"><span>Trạng thái kiểm duyệt</span><StatusBadge status={profile.data?.verification_status ?? 'pending'} /></div><div className="form-grid"><label><span>Tên cơ sở</span><input name="business_name" defaultValue={profile.data?.business_name} /></label><label><span>SĐT kinh doanh</span><input name="business_phone" defaultValue={profile.data?.business_phone} /></label><label><span>Địa chỉ kinh doanh</span><input name="business_address" defaultValue={profile.data?.business_address} /></label><label><span>Giấy phép</span><input name="business_license" defaultValue={profile.data?.business_license ?? ''} /></label></div><label><span>Giới thiệu</span><textarea name="description" defaultValue={profile.data?.description ?? ''} /></label>{update.isSuccess && <div className="notice notice--success">Đã lưu hồ sơ cơ sở.</div>}{update.isError && <div className="notice notice--error">{errorMessage(update.error)}</div>}<button className="button button--brand">Lưu hồ sơ</button></form></>
}

function Stat({ label, value }: { label: string; value: string | number }) { return <article className="stat"><span>{label}</span><strong>{value}</strong></article> }
function BookingTable({ bookings, actions }: { bookings: Booking[]; actions?: (booking: Booking) => React.ReactNode }) { return <div className="table-wrap"><table><thead><tr><th>Đơn & sân</th><th>Khách hàng</th><th>Lịch chơi</th><th>Giá trị</th><th>Trạng thái</th>{actions && <th />}</tr></thead><tbody>{bookings.map((booking) => <tr key={booking.id}><td><small>#BK-{booking.id}</small><strong>{booking.field?.name}</strong></td><td>{booking.customer?.name ?? '—'}</td><td>{new Date(booking.booking_date).toLocaleDateString('vi-VN')}<small>{booking.time_slot?.start_time} – {booking.time_slot?.end_time}</small></td><td>{currency.format(booking.total_price)}đ</td><td><StatusBadge status={booking.status} /></td>{actions && <td><div className="row-actions">{actions(booking)}</div></td>}</tr>)}</tbody></table></div> }
