import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Building2, CalendarDays, ChartNoAxesCombined, FolderTree, MessageSquareText, ShieldCheck, UsersRound } from 'lucide-react'
import { Fragment, useState, type FormEvent } from 'react'
import { api, initializeCsrf } from '../../api/client'
import { errorMessage } from '../../api/errors'
import { StatusBadge } from '../../components/StatusBadge'
import type { AdminDashboard, ApiEnvelope, Booking, Category, OwnerProfile, Paginated, Review, SportsField, User } from '../../types/api'
import { Empty, PageTitle } from '../customer/CustomerPages'

const currency = new Intl.NumberFormat('vi-VN')

export function AdminDashboardPage() {
  const dashboard = useQuery({ queryKey: ['admin', 'dashboard'], queryFn: async () => (await api.get<ApiEnvelope<AdminDashboard>>('/admin/dashboard')).data.data })
  const data = dashboard.data
  return <><PageTitle icon={<ChartNoAxesCombined />} kicker="Toàn hệ thống" title="Trung tâm điều hành" copy="Một góc nhìn rõ ràng cho người dùng, nguồn cung và giao dịch." /><div className="stats-grid"><Stat label="Khách hàng" value={data?.total_customers ?? 0} /><Stat label="Chủ sân" value={data?.total_field_owners ?? 0} note={`${data?.pending_owners ?? 0} chờ duyệt`} /><Stat label="Sân thể thao" value={data?.total_fields ?? 0} note={`${data?.pending_fields ?? 0} chờ duyệt`} /><Stat label="Doanh thu" value={`${currency.format(data?.total_revenue ?? 0)}đ`} /></div><section className="data-panel"><div className="data-panel__head"><div><span>Xếp hạng</span><h2>Sân được đặt nhiều nhất</h2></div></div><div className="ranking">{data?.most_booked_fields.map((field, index) => <article key={field.id}><b>{String(index + 1).padStart(2, '0')}</b><div><strong>{field.name}</strong><small>{field.address}</small></div><span>{field.bookings_count} lượt đặt</span></article>)}</div></section></>
}

export function AdminUsersPage() {
  const client = useQueryClient(); const [keyword, setKeyword] = useState(''); const [role, setRole] = useState('')
  const users = useQuery({ queryKey: ['admin', 'users', keyword, role], queryFn: async () => (await api.get<Paginated<User>>(`/admin/users?keyword=${encodeURIComponent(keyword)}&role=${role}`)).data })
  const toggle = useMutation({ mutationFn: async (user: User) => { await initializeCsrf(); return api.patch(`/admin/users/${user.id}/toggle`) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'users'] }) })
  return <><PageTitle icon={<UsersRound />} kicker="Tài khoản" title="Cộng đồng SportHub" copy="Tra cứu và kiểm soát trạng thái truy cập của người dùng." /><div className="toolbar"><input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tên, email, số điện thoại" /><select value={role} onChange={(e) => setRole(e.target.value)}><option value="">Tất cả vai trò</option><option value="customer">Khách hàng</option><option value="field_owner">Chủ sân</option></select></div><DataTable heads={['Người dùng','Liên hệ','Vai trò','Trạng thái','']} rows={users.data?.data.map((user) => [<strong key="user">{user.name}</strong>,<Fragment key="contact"><span>{user.email}</span><small>{user.phone}</small></Fragment>,user.role === 'field_owner' ? 'Chủ sân' : 'Khách hàng',<StatusBadge key="status" status={user.is_active ? 'approved' : 'inactive'} />,<button key="action" className={`button ${user.is_active ? 'button--danger' : 'button--brand'}`} onClick={() => toggle.mutate(user)}>{user.is_active ? 'Khóa' : 'Mở khóa'}</button>]) ?? []} /></>
}

export function AdminOwnersPage() {
  const client = useQueryClient(); const profiles = useQuery({ queryKey: ['admin', 'owners'], queryFn: async () => (await api.get<Paginated<OwnerProfile>>('/admin/field-owners')).data })
  const verify = useMutation({ mutationFn: async ({ profile, status }: { profile: OwnerProfile; status: string }) => { await initializeCsrf(); return api.patch(`/admin/field-owners/${profile.id}/verify`, { status }) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'owners'] }) })
  return <><PageTitle icon={<ShieldCheck />} kicker="Kiểm duyệt" title="Hồ sơ chủ sân" copy="Xác minh thông tin cơ sở trước khi cấp quyền vận hành." /><DataTable heads={['Chủ sân','Cơ sở','Địa chỉ','Trạng thái','']} rows={profiles.data?.data.map((profile) => [<Fragment key="owner"><strong>{profile.user?.name}</strong><small>{profile.user?.email}</small></Fragment>,<Fragment key="business"><strong>{profile.business_name}</strong><small>{profile.business_phone}</small></Fragment>,profile.business_address,<StatusBadge key="status" status={profile.verification_status} />,profile.verification_status === 'pending' ? <div key="action" className="row-actions"><button className="button button--danger" onClick={() => verify.mutate({ profile, status: 'rejected' })}>Từ chối</button><button className="button button--brand" onClick={() => verify.mutate({ profile, status: 'approved' })}>Duyệt</button></div> : 'Đã xử lý']) ?? []} /></>
}

export function AdminFieldsPage() {
  const client = useQueryClient(); const [status, setStatus] = useState(''); const fields = useQuery({ queryKey: ['admin', 'fields', status], queryFn: async () => (await api.get<Paginated<SportsField>>(`/admin/fields${status ? `?status=${status}` : ''}`)).data })
  const verify = useMutation({ mutationFn: async ({ field, status: next }: { field: SportsField; status: string }) => { await initializeCsrf(); return api.patch(`/admin/fields/${field.id}/verify`, { status: next }) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'fields'] }) })
  return <><PageTitle icon={<Building2 />} kicker="Nguồn cung" title="Kiểm duyệt sân" copy="Đảm bảo mỗi sân xuất hiện đều có thông tin đáng tin cậy." /><div className="toolbar"><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Tất cả</option><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="rejected">Từ chối</option></select></div><DataTable heads={['Sân','Chủ sân','Phân loại','Giá/giờ','Trạng thái','']} rows={fields.data?.data.map((field) => [<Fragment key="field"><strong>{field.name}</strong><small>{field.address}</small></Fragment>,field.owner?.name,field.field_type?.name,`${currency.format(field.price_per_hour)}đ`,<StatusBadge key="status" status={field.status} />,field.status === 'pending' ? <div key="action" className="row-actions"><button className="button button--danger" onClick={() => verify.mutate({ field, status: 'rejected' })}>Từ chối</button><button className="button button--brand" onClick={() => verify.mutate({ field, status: 'approved' })}>Duyệt</button></div> : 'Đã xử lý']) ?? []} /></>
}

export function AdminBookingsPage() {
  const [status, setStatus] = useState(''); const bookings = useQuery({ queryKey: ['admin', 'bookings', status], queryFn: async () => (await api.get<Paginated<Booking>>(`/admin/bookings${status ? `?status=${status}` : ''}`)).data })
  return <><PageTitle icon={<CalendarDays />} kicker="Giao dịch" title="Toàn bộ lượt đặt" copy="Theo dõi lịch chơi và giá trị giao dịch trong hệ thống." /><div className="toolbar"><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Mọi trạng thái</option><option value="pending">Chờ xử lý</option><option value="confirmed">Đã xác nhận</option><option value="completed">Hoàn thành</option><option value="cancelled">Đã hủy</option></select></div><DataTable heads={['Mã & sân','Khách hàng','Lịch chơi','Giá trị','Trạng thái']} rows={bookings.data?.data.map((booking) => [<Fragment key="booking"><small>#BK-{booking.id}</small><strong>{booking.field?.name}</strong></Fragment>,booking.customer?.name,<Fragment key="schedule">{new Date(booking.booking_date).toLocaleDateString('vi-VN')}<small>{booking.time_slot?.start_time} – {booking.time_slot?.end_time}</small></Fragment>,`${currency.format(booking.total_price)}đ`,<StatusBadge key="status" status={booking.status} />]) ?? []} /></>
}

export function AdminReviewsPage() {
  const client = useQueryClient(); const reviews = useQuery({ queryKey: ['admin', 'reviews'], queryFn: async () => (await api.get<Paginated<Review>>('/admin/reviews')).data })
  const toggle = useMutation({ mutationFn: async (review: Review) => { await initializeCsrf(); return api.patch(`/admin/reviews/${review.id}/toggle`) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'reviews'] }) })
  return <><PageTitle icon={<MessageSquareText />} kicker="Nội dung" title="Đánh giá cộng đồng" copy="Lắng nghe phản hồi và ẩn nội dung không phù hợp." /><div className="review-grid">{reviews.data?.data.map((review) => <article className="review-card" key={review.id}><div><div className="avatar">{review.user?.name.slice(0,1)}</div><span><strong>{review.user?.name}</strong><small>{review.field?.name}</small></span><StatusBadge status={review.is_visible ? 'approved' : 'inactive'} /></div><b>{'★'.repeat(review.rating)}</b><p>“{review.comment}”</p><button className={`button ${review.is_visible ? 'button--danger' : 'button--brand'}`} onClick={() => toggle.mutate(review)}>{review.is_visible ? 'Ẩn đánh giá' : 'Hiển thị lại'}</button></article>)}</div>{!reviews.isPending && !reviews.data?.data.length && <Empty text="Chưa có đánh giá trong hệ thống." />}</>
}

export function AdminCategoriesPage() {
  const client = useQueryClient(); const categories = useQuery({ queryKey: ['admin', 'categories'], queryFn: async () => (await api.get<{ data: Category[] }>('/admin/categories')).data.data })
  const createCategory = useMutation({ mutationFn: async (payload: Record<string,string>) => { await initializeCsrf(); return api.post('/admin/categories', payload) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'categories'] }) })
  const createType = useMutation({ mutationFn: async (payload: Record<string,string>) => { await initializeCsrf(); return api.post('/admin/field-types', payload) }, onSuccess: () => client.invalidateQueries({ queryKey: ['admin', 'categories'] }) })
  const submit = (event: FormEvent<HTMLFormElement>, mutation: typeof createCategory | typeof createType) => { event.preventDefault(); mutation.mutate(Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>); event.currentTarget.reset() }
  return <><PageTitle icon={<FolderTree />} kicker="Cấu trúc dữ liệu" title="Danh mục & loại sân" copy="Tổ chức các môn chơi theo cách khách hàng dễ tìm nhất." /><div className="category-admin"><div><form className="panel-form" onSubmit={(e) => submit(e, createCategory)}><h2>Thêm môn thể thao</h2><label><span>Tên danh mục</span><input name="name" required /></label><label><span>Biểu tượng</span><input name="icon" placeholder="⚽" /></label><label><span>Mô tả</span><textarea name="description" /></label>{createCategory.isError && <div className="notice notice--error">{errorMessage(createCategory.error)}</div>}<button className="button button--dark">Tạo danh mục</button></form><form className="panel-form" onSubmit={(e) => submit(e, createType)}><h2>Thêm loại sân</h2><label><span>Danh mục</span><select name="sport_category_id" required>{categories.data?.map((cat) => <option value={cat.id} key={cat.id}>{cat.icon} {cat.name}</option>)}</select></label><label><span>Tên loại sân</span><input name="name" required /></label>{createType.isError && <div className="notice notice--error">{errorMessage(createType.error)}</div>}<button className="button button--brand">Tạo loại sân</button></form></div><section className="data-panel"><div className="data-panel__head"><div><span>Cấu trúc hiện tại</span><h2>{categories.data?.length ?? 0} bộ môn</h2></div></div><div className="category-tree">{categories.data?.map((category) => <article key={category.id}><b>{category.icon}</b><div><strong>{category.name}</strong><p>{category.description}</p><small>{category.field_types_count} loại sân</small></div></article>)}</div></section></div></>
}

function Stat({ label, value, note }: { label: string; value: string | number; note?: string }) { return <article className="stat"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</article> }
function DataTable({ heads, rows }: { heads: string[]; rows: React.ReactNode[][] }) { return <section className="data-panel"><div className="table-wrap"><table><thead><tr>{heads.map((head, index) => <th key={index}>{head}</th>)}</tr></thead><tbody>{rows.map((cells, row) => <tr key={row}>{cells.map((cell, column) => <td key={column}>{cell}</td>)}</tr>)}</tbody></table></div>{rows.length === 0 && <Empty text="Không có dữ liệu phù hợp." />}</section> }
